### PR TITLE
ansible: It's called tmpwatch in OpenSUSE

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Review by dmick — COMMENTED** [review]
So, I'm confused how this works.  It appears that --runtime 0 is an argument to tmp_cleaner_name, but tmpwatch on CentOS8 at least doesn't document such an option.  tmpreaper on Ubuntu does.  It seems like the command also needs to be parameterized.

**Comment by djgalloway** [comment]
You didn't need to go read the man page.  We're just setting a var :stuck_out_tongue_closed_eyes:.

But you are right.  And fair enough.  I will fix in a separate PR.

**Comment by djgalloway** [comment]
Crap.  I accidentally pushed to this branch.  I can just change the PR title?

**Comment by djgalloway** [comment]
Can merge https://github.com/ceph/ceph-build/pull/1849 after this one.

**Review by dmick — APPROVED** [review]

**Pull request merged**
