### PR TITLE
Replace obsolete "include:' in upstream ansible tasks

### PR DESCRIPTION
**Pull request by dmick**
Clone the upstream ansible task repos "Mayeu/ansible-playbook-rabbitmq" and "andrewschoen/ansible-playbook-sensu" (already a clone of "Mayeu/ansible-playbook-sensu"); add commits to transition from "include:" to "import_tasks:", and use the new clones as the ansible-galaxy dependency in this repo's pull-request tests.

also, add a trigger phrase to rerun the tests.

### CODE REVIEW

**Comment by dmick** [comment]
retest

**Comment by tchaikov** [comment]
@dmick could you please paste a link to the test failure for me and for the posterities ? and probably quote part of the error in the first commit. so we can connect the symptom to the cure?

**Comment by dmick** [comment]
Well, I can cut and paste (the builds will disappear):

```
+ /tmp/venv.0fxbWH2RE5/bin/ansible-playbook -i 127.0.0.1, /home/jenkins-build/build/workspace/ceph-build-pull-requests/ansible/examples/sensu.yml --syntax-check
ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.

The error appears to be in '/home/jenkins-build/build/workspace/ceph-build-pull-requests/ansible/examples/roles/Mayeu.sensu/tasks/main.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include: common.yml
  ^ here
```

**Comment by dmick** [comment]
we've had to fix this in numerous places in our own ansible code; this is new because it's fixing it in someone else's, but not new to Ceph

**Comment by dmick** [comment]
it's worth noting that these clones should probably be moved to the ceph organization.

**Comment by dmick** [comment]
@tchaikov are you happy with this?  Can we merge?

**Comment by tchaikov** [comment]
@dmick i didn't get a chance to look into this change last night. as i am not familiar with the related workflow and ansible, i need a relatively large chunk of time to prepare myself and audit the change. will do later today.

**Comment by dmick** [comment]
oh.  maybe this will save a little bit:

1) ansible obsoleted "include:" and provides several replacements.  For all the ways we typically use include, the replacement "import_tasks:" seems to work.  Simple transliteration.

2) the complication with this PR job is that it uses several roles from the internet, specifically this account named Mayeu, to install sensu and rabbitmq.  Years ago Andrew had forked the sensu-role-repo (ansible-playbook-sensu) and so our ansible-galaxy requirements file referred to his fork and the original for ansible-playbook-rabbitmq.  Today, both of those playbooks were still using include:, and so to make them work with newer ansible, we had to do the same transliterations on the third-party playbooks.  To do that, I created a new revision in andrew's fork, and created my own fork of the rabbitmq repo, and made the include:->import_tasks: change in both those forks.

**Review by guits — APPROVED** [review]

**Comment by dmick** [comment]
@tchaikov I'm going to go with @guits 's review here; you needn't worry about this unless you want to

**Pull request merged**
