### PR TITLE
nfs-ganesha*: backup golden pbuilder base.tgz before changing it

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Review by badone — APPROVED** [review]
LGTM

**Comment by alimaredia** [comment]
I think this one is up @tserlin 's ally

**Comment by dmick** [comment]
I mean, I think this is a good idea, but I think this ought to be done generically for all the builds that use pbuilder; there may well be lurking inconsistencies and avoidable build failures happening in the various other projects as well (including ceph dev or stable releases).

**Comment by tchaikov** [comment]
@dmick i'd like to help. but can we start with this `nfs-ganesha*`, and only backup/restore if necessary?

**Comment by dmick** [comment]
It seems like doing this generically is even easier, and pretty easy to make safe: build a gold image, update it, and then don't touch it (maybe with periodic time-based updates) for the actual build, but rather always make a copy

**Comment by tchaikov** [comment]
@dmick hi Dan,  is this change still not relevant? if not. i will close it.

**Comment by dmick** [comment]
I cleared all the cached tarballs, and they immediately got polluted on virtually all the build machines.  I'm concerned for all the builds but haven't experienced any actual breakage recently.

**Comment by tchaikov** [comment]
thank you Dan. glad to learn that the builds survived the polluted chroot env =)

**Pull request closed without merging**
