### PR TITLE
ceph-cbt-lint: add cbt lint test

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
this change depends on https://github.com/ceph/cbt/pull/226

**Comment by tchaikov** [comment]
see also https://github.com/ceph/githubcheck

**Comment by djgalloway** [comment]
> see also https://github.com/ceph/githubcheck

Is this the same as https://github.com/alfredodeza/github-status ?

**Comment by tchaikov** [comment]
> > see also https://github.com/ceph/githubcheck
> 
> Is this the same as https://github.com/alfredodeza/github-status ?

no. they are different. status versus check. see https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-status-checks#types-of-status-checks-on-github

**Comment by tchaikov** [comment]
@epuertat @djgalloway ping?

**Comment by tchaikov** [comment]
@jdurgin i recall that you mentioned the GitHub check the other day.

**Review by djgalloway — APPROVED** [review]

**Pull request merged**
