### PR TITLE
ceph-dev-trigger: include octopus branch

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
https://github.com/ceph/ceph-build/blob/master/ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml should also reflect these changes

**Comment by tchaikov** [comment]
@djgalloway i did update `ceph-dev-new-trigger.yml` . could you be more specific on what change i am missing?

**Comment by djgalloway** [comment]
Sorry, I think I commented before you edited ceph-dev-new-trigger.  That job's good to go.

Doesn't this need to be split out though?  https://github.com/ceph/ceph-build/blob/bc2daa700329365fceed3ae3eda9470292d26104/ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml#L115-L146

**Comment by tchaikov** [comment]
@dgalloway updated and repushed.

**Comment by djgalloway** [comment]
@tchaikov you're the best!

**Pull request merged**
