### PR TITLE
ceph-ansible-pipeline: remove one step

### PR DESCRIPTION
**Pull request by guits**
save some times by removing one step, let's run everything in one step.

Otherwise, it's ~4h of CI testing for 1 PR, removing this step will make
amount of time divided per 2.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
> which node label should we use to achieve that?

The label is `ovh`

:smiley:

**Comment by djgalloway** [comment]
Oh, and if you need more resources (and NVMe isn't a requirement) I can make that happen.

**Comment by leseb** [comment]
Superseded by https://github.com/ceph/ceph-build/pull/1102?

**Comment by guits** [comment]
closing this since #1102 has been merged

**Pull request closed without merging**
