### PR TITLE
ceph-volume-ansible-prs: do not use raw xml, use the jjb option for ghprb

### PR DESCRIPTION
**Pull request by alfredodeza**
Signed-off-by: Alfredo Deza <adeza@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
That's definitely the "what"

but why

In particular, are we working around a bug in JJB upstream that will soon be resolved, so we can eventually revert this?

**Comment by alfredodeza** [comment]
the newer version of JJB allows to declare it as part of the plugin, the older version didn't

**Comment by ktdreyer** [comment]
Why don't we upgrade JJB? What's the version that will allow us to revert?

**Comment by djgalloway** [comment]
That's what we did here: https://github.com/ceph/ceph-build/pull/819/commits/4f10012571b120e01854fae49be4d43f382787f1

**Comment by ktdreyer** [comment]
thanks @djgalloway !

**Pull request merged**
