### PR TITLE
ceph-installer-tests: do not send emails on job completion

### PR DESCRIPTION
**Pull request by andrewschoen**
We don't have a mail server setup, so lets remove this for now.

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
hang on one second, I think I might get this working :) I promise

**Comment by alfredodeza** [comment]
I worked a bit on getting this on the master instance, and although it can send emails out, the problem is that slaves want to either send email directly or connect to an SMTP server. If the SMTP server is on the master it means it should have authentication enabled, and SMTP authentication is not very easy to setup.

This doesn't error anymore, but it doesn't send emails either.

**Comment by alfredodeza** [comment]
Adding more nightlies to Jenkins means this needs to be revisited. We need to have some sort of email notifications. @djgalloway do you have any ideas on how we could try to make this work?

**Comment by djgalloway** [comment]
@alfredodeza - Refresh my memory?  What made us think the slaves were trying to send mail directly?

**Comment by alfredodeza** [comment]
ceph-installer no longer exists, and emails are starting to go out

**Pull request closed without merging**
