### PR TITLE
jenkins-job-builder: Delete stale jobs

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
(Rebased and fixed spacing)

**Comment by djgalloway** [comment]
@alfredodeza @andrewschoen sooo I know this PR is kinda sketchy testing in prod and all...  I could always comment the `jenkins-jobs` line and open a new PR once we see the results of the `echo`s.

**Comment by djgalloway** [comment]
See https://2.jenkins.ceph.com/job/jenkins-job-builder/91/console

I pasted the new build script into 2.jenkins.ceph.com jenkins-job-builder's config but left out the actual delete command.  You can see the jobs that would've been deleted in the job output.

**Comment by djgalloway** [comment]
Same thing for https://jenkins.ceph.com/job/jenkins-job-builder/796/console

Nothing actually deleted.  Just Ctrl+F "Deleting" for what would've been deleted.

**Comment by ktdreyer** [comment]
This is great

**Pull request merged**
