### PR TITLE
samba: remove cruft, add missing dependencies

### PR DESCRIPTION
**Pull request by dmick**
Signed-off-by: Dan Mick <dan.mick@redhat.com>

### CODE REVIEW

**Comment by dmick** [comment]
Tested manually, builds successfully:  https://jenkins.ceph.com/job/samba/39/

**Comment by alfredodeza** [comment]
can you rebase this please?

**Comment by dmick** [comment]
https://github.com/ceph/ceph-build/pull/728 apparently does some of what this does, and makes conflicts.  That'll teach me to help out.

I think https://github.com/ceph/ceph-build/pull/728 is wrong; the PAM package on Ubuntu is what I'd done here, libpam0g-dev: 

http://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libpam0g-dev&searchon=names

**Comment by b-ranto** [comment]
@dmick if you do apt-get install libpam-dev, it will actually install libpam0g-dev on xenial, libpam-dev is probably some kind of meta package or libpam0g-dev provides libpam-dev or something like that. I have never been too sure about how to handle these versioned libraries in Debian/Ubuntu (i.e. whether to install them by meta package or directly). :-/

Nice catch on the double DIST, I was wondering where that was coming from. I am not sure how I could have not noticed it. :-)

Anyway, I have cherry-picked the double DIST commit to https://github.com/ceph/ceph-build/pull/729 that contains a couple of commits for triggered builds and I will merge that one.

**Comment by b-ranto** [comment]
I guess we can close now.

**Comment by dmick** [comment]
re: pkg name: you are correct.  libpam0g-dev "Provides" libpam-dev.  Good enough for me.

**Pull request closed without merging**
