### PR TITLE
nfs-ganesha/samba: disable ceph triggered builds of nfs-ganesha & samba

### PR DESCRIPTION
**Pull request by alimaredia**
Signed-off-by: Ali Maredia <amaredia@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
can  you just disable this job for now? e.g.

    disabled: true

**Comment by alimaredia** [comment]
@alfredodeza take a look at it now

**Comment by alfredodeza** [comment]
@alimaredia you need to disable for the jobs that 'trigger' the builds. Yes: disabling will prevent you from doing that. I thought that for samba we had 'trigger' jobs?

**Comment by alimaredia** [comment]
Changed the title so that this PR isn't merged unless the decision is made to disable those builds.

**Comment by alimaredia** [comment]
@alfredodeza removed the DNM tag, this is good to merge on my end

**Comment by alfredodeza** [comment]
@alimaredia you need a rebase I think

**Comment by alfredodeza** [comment]
I think we are good with this now that they are time-based

**Pull request closed without merging**
