### PR TITLE
tcmu-runner: remove shaman repo file after build

### PR DESCRIPTION
**Pull request by dillaman**
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by dillaman** [comment]
@alfredodeza Am I missing something? I see the following error when it tried to remove the repo file: https://jenkins.ceph.com/job/tcmu-runner/10/console

**Comment by alfredodeza** [comment]
Yep, you are building on 'master':

    Building on master in workspace /var/lib/jenkins/jobs/tcmu-runner/workspace

Which can happen if you don't specify what type of node you want. For example:
https://github.com/ceph/ceph-build/blob/master/ceph-installer-coverage/config/definitions/ceph-installer-coverage.yml#L3

trusty, centos, small, large, x86_64, are a few of the labels you can use to describe what you need.

**Comment by dillaman** [comment]
The samba definition doesn't have anything like that and it appears to work: https://github.com/ceph/ceph-build/blob/master/samba/config/definitions/samba.yml

**Comment by alfredodeza** [comment]
That job is a "matrix" job:

    project-type: matrix

That means that it can run in master, but it is like a "parent" job, the `matrix` will extrapolate the `label-expression` into different machines:

https://github.com/ceph/ceph-build/blob/master/samba/config/definitions/samba.yml#L49-L68

You end up with something like: <parent (matrix) job> -> multiple distros/versions/archs builds+machines

**Pull request merged**
