### PR TITLE
ansible: Disable daily apt transaction on Ephemeral slaves

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Review by smithfarm — APPROVED** [review]
having test slaves update themselves automatically on a daily basis seems like a recipe for trouble, so yes. if this change disables that, I'm for it.

**Comment by smithfarm** [comment]
@djgalloway Thanks for taking care.

**Comment by djgalloway** [comment]
> having test slaves update themselves automatically on a daily basis seems like a recipe for trouble, so yes. if this change disables that, I'm for it.

Yep, that's what was happening in the jobs you pinged me about.  The slave would come up, connect to Jenkins, then `unattended-upgrades` or the systemd timer would start an `apt` transaction which interrupted the Jenkins job.  This PR stops that.

**Comment by tchaikov** [comment]
@djgalloway thanks for looking into this. i had been wondering who's using dpkg / apt while the jenkins slave was running test..

**Pull request merged**
