### PR TITLE
ceph-api: do not build/run tests for api tests

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@alfonsomthd

**Comment by tchaikov** [comment]
this changeset contains #1626

**Comment by alfonsomthd** [comment]
> this changeset contains #1626

If we merge this, then the follow-up [action items](https://github.com/ceph/ceph-build/pull/1626#issue-451277091) must be done.

**Comment by tchaikov** [comment]
@epuertat i am okay closing your PR.

**Pull request merged**
