### PR TITLE
remove the RELEASE checkbox on the ceph-next job

### PR DESCRIPTION
**Pull request by andrewschoen**
We do not sign with jenkins anymore

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
can you add this for (current) ceph as well?

**Comment by andrewschoen** [comment]
@alfredodeza sure thing, updated.

**Comment by ktdreyer** [comment]
LGTM! thank you

**Comment by ktdreyer** [comment]
Whoops, I fumbled the `hub` command and rebased instead of merging. These commits are now in master:

6cc230f8870008e82ddb780f3c9ebc25872ac0a0
99da5132b22313d81094812345e6246c9657332c

**Pull request closed without merging**
