### PR TITLE
ceph-pull-requests: remove WITH_ZBD

### PR DESCRIPTION
**Pull request by Svelar**
Fixes: https://tracker.ceph.com/issues/64962

Because of: https://github.com/ceph/ceph/pull/55054

### CODE REVIEW

**Comment by dmick** [comment]
Looks like it still exists in ceph's src/script/run-make.sh as well, and should probably be removed from there too.  @pereman2 do you agree about both deletions?

**Comment by pereman2** [comment]
@dmick agree!

**Comment by Svelar** [comment]
> Looks like it still exists in ceph's src/script/run-make.sh as well, and should probably be removed from there too. @pereman2 do you agree about both deletions?

Related: https://github.com/ceph/ceph/pull/56283

**Comment by dmick** [comment]
@Svelar please file a followup for run-make.sh

**Pull request merged**
