### PR TITLE
[WIP] Added Jenkins job for dashboard end-to-end tests

### PR DESCRIPTION
**Pull request by callithea**
This Jenkins job should be triggered for pull-requests labeled with "dashboard" and should execute the frontend (e2e) tests. 
To be able to execute the tests it's required to have a browser installed (in this case Google Chrome).

The "ceph-dashboard-pull-requests.yml" is based on the [ceph-pull-requests.yml](https://github.com/ceph/ceph-build/blob/master/ceph-pull-requests/config/definitions/ceph-pull-requests.yml) file with some modifications.

Signed-off-by: Laura Paduano lpaduano@suse.com

### CODE REVIEW

**Comment by alfredodeza** [comment]
We don't normally use open pull requests for active development. Could you close this and re-open when you feel this is ready? Otherwise it is triggering tests that aren't really needed.

**Comment by callithea** [comment]
Sure, I'll close it. @alfredodeza is there another way to test this beforehand?

I found [this section](https://github.com/ceph/ceph-build#testing-jjb-changes-by-hand-before-merging-to-master) in the README but it's about testing JJB changes so I wasn't sure if it would also make sense for a new Jenkins job?

**Comment by alfredodeza** [comment]
There is no way to test this beforehand :(

I would recommend to get this as ready as you can, and then we can review and iterate over if you need additional fixes that were not detected in the review process

**Comment by callithea** [comment]
Okay, thanks! :)

**Pull request closed without merging**
