### PR TITLE
scripts,ceph-dev-new*: add "crimson" flavor

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
the crimson flavor of ceph builds fine at https://shaman.ceph.com/builds/ceph/wip-kefu-testing/8e370f262d13a6ae988bd4dbbd1a2a9acfd845b6/crimson/154726/

**Comment by tchaikov** [comment]
FTBFS at https://shaman.ceph.com/builds/ceph/add_http_endpoint_tests/c96141421906896e7560f5f308cd100f1272b24d/crimson/154756/

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-crimson-packaging/4e016d701093f6e90ea7cee3b7da0eee66434619/

**Comment by tchaikov** [comment]
rebased.

**Comment by xiexingguo** [comment]
@tchaikov FYI:
Seems shaman now stops to work for both flavor ubuntu and crimson.
https://shaman.ceph.com/builds/ceph/

I have no idea if it is related, and please ignore the noise if not.

**Comment by tchaikov** [comment]
thanks for the heads-up. #1319 should address the issue.

**Pull request merged**
