### PR TITLE
ceph-dev*: build crimson on centos9 (main and reef)

### PR DESCRIPTION
**Pull request by Matan-B**

### CODE REVIEW

**Review by dmick — COMMENTED** [review]
Do we know that it builds cleanly on both archs?

**Comment by athanatos** [comment]
@dmick Is there a way to test that prior to merging this?

**Comment by dmick** [comment]
Of course private builds are *a* way, but we can also create a copy of the job with these changes and send it to Jenkins manually, setting it to trigger only on request.  https://github.com/ceph/ceph-build#testing-jjb-changes-by-hand-before-merging-to-main

**Comment by Matan-B** [comment]
> Of course private builds are _a_ way, but we can also create a copy of the job with these changes and send it to Jenkins manually, setting it to trigger only on request. https://github.com/ceph/ceph-build#testing-jjb-changes-by-hand-before-merging-to-main

Hey @dmick, Thanks for the link.

`jenkins-jobs --conf ~/.jenkins_jobs.ini update ceph-dev-cron/config/definitions/ceph-dev-cron.yml` stage returns some errors which seems to be caused because: `Matan-B is missing the Overall/Read permission` 
What can I do to get the required permissions?

```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://jenkins.ceph.com/crumbIssuer/api/json 
..
jenkins.JenkinsException: Error in request. Possibly authentication failed [403]: Forbidden
```

**Comment by dmick** [comment]
Jenkins write permissions are only available to a few (for obvious reasons); I don't know who all, but we probably don't want to expand them.  If your own builds succeed on centos9 we can push this.

**Comment by dmick** [comment]
Do your own builds succeed on centos9?

**Comment by Matan-B** [comment]
> Do your own builds succeed on centos9?

IIUC you refer to local build so yes. There are some dependencies we will need to update but builds look ok.
```
  cluster:
    id:     3fdae197-0ce1-4120-81a4-aa59ed7bd33a
    health: HEALTH_WARN
            1 pool(s) have no replicas configured
 
  services:
    mon: 1 daemons, quorum a (age 2m)
    mgr: x(active, since 2m)
    osd: 1 osds: 1 up (since 2m), 1 in (since 2m)
 
  data:
    pools:   1 pools, 1 pgs
    objects: 2 objects, 449 KiB
    usage:   1.0 GiB used, 100 GiB / 101 GiB avail
    pgs:     1 active+clean
 
[<> build]# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

**Review by dmick — APPROVED** [review]

**Pull request merged**
