### PR TITLE
ceph-release-rpm: add CentOS 9 build

### PR DESCRIPTION
**Pull request by epuertat**
Builds CentOS 9 build for ceph-release rpm.

### CODE REVIEW

**Comment by dmick** [comment]
I think we'll want to do this if/when we release an official build for centos9.  I'm not sure what the plan is; maybe reef?

**Comment by epuertat** [comment]
> I think we'll want to do this if/when we release an official build for centos9. I'm not sure what the plan is; maybe reef?

I thought we already were, or at least I see a [Quincy CentOS 9 repo available at Ceph Downloads](https://download.ceph.com/rpm-17.2.5/el9/noarch/)...

**Comment by epuertat** [comment]
Thanks, @ktdreyer. I'll leave then up to @dmick whether to merge this or not/later.

**Comment by ktdreyer** [comment]
Justin added most of the `centos9` configuration upstream a while ago in https://github.com/ceph/ceph-build/pull/2003 . I guess that we just missed adding this one `centos9` line here.

**Comment by dmick** [comment]
OK.  I don't think our centos9 plan is what you'd call fleshed out, but maybe this unblocks stuff

**Comment by epuertat** [comment]
Thank you, guys! I guess that for 17.2.6 we'll have this RPM first released for EL9.

**Pull request merged**
