### PR TITLE
kernel: update KConfig to 5.7.0-rc5-ish

### PR DESCRIPTION
**Pull request by lxbsz**
There has some options' types in higher kernel version has changed,
such as without `make menuconfig` we can get:

```
scripts/kconfig/mconf  Kconfig
.config:641:warning: symbol value 'm' invalid for CPU_FREQ_STAT
.config:743:warning: symbol value 'm' invalid for HOTPLUG_PCI_SHPC
.config:890:warning: symbol value 'm' invalid for NF_CT_PROTO_DCCP
.config:891:warning: symbol value 'm' invalid for NF_CT_PROTO_GRE
.config:892:warning: symbol value 'm' invalid for NF_CT_PROTO_SCTP
.config:893:warning: symbol value 'm' invalid for NF_CT_PROTO_UDPLITE
.config:919:warning: symbol value 'm' invalid for NF_NAT_REDIRECT
.config:922:warning: symbol value 'm' invalid for NF_TABLES_INET
.config:1093:warning: symbol value 'm' invalid for NF_TABLES_IPV4
.config:1097:warning: symbol value 'm' invalid for NF_TABLES_ARP
.config:1134:warning: symbol value 'm' invalid for NF_TABLES_IPV6
.config:2336:warning: symbol value 'm' invalid for HW_RANDOM_TPM
configuration written to .config

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.
```

And if we do nothing in `make menuconfig`, the above invalid type
options will be disabled as default, so this is why we are hitting
the iptable INPUT/FORWARD/OUTPUT chains not support with the latest
upstream kernel.

Fixes: https://tracker.ceph.com/issues/45531
Signed-off-by: Xiubo Li <xiubli@redhat.com>

### CODE REVIEW

**Comment by lxbsz** [comment]
Generate the config files by using `cd /data/linux/ && /data/ceph-build/kernel/build/kernel-config-deb.sh && make menuconfig` and then enable the netfilter options needed in `make menuconfig`.

This changes has refered to @jtlayton's previous PR https://github.com/ceph/ceph-build/pull/1568.

**Comment by lxbsz** [comment]
> I thought we agreed on manually editing in the netfilter stuff into the existing configs. If so, the diff should be just a dozen lines, not a couple thousand.

The new lines are the options added in new kernel  or deleted by new kernel. Even we don't add/delete them here, they will be added/deleted anyway when we are building the kernel from source.

And I have checked this with ` rpm2cpio kernel-5.7.0_rc5_ceph_g2df39dc136cc-1.x86_64.rpm | cpio -idmv ./boot/config-5.7.0-rc5-ceph-g2df39dc136cc`, the are the same.

Will it make sense ? If we don't like this I will only change the netfilter ones in next version.

**Comment by idryomov** [comment]
Did you check deb as well?

**Comment by lxbsz** [comment]
> Did you check deb as well?



> Did you check deb as well?

yeah, checked the deb package from `https://4.chacra.ceph.com/r/kernel/testing/1457be129a637ec30e6f528597e4629faf76db3a/ubuntu/bionic/flavors/default/pool/main/l/linux-5.7.0-rc1-ceph-g1457be129a63/`

Get the config from dep package:

`dpkg-deb --fsys-tarfile linux-headers-5.7.0-rc1-ceph-g1457be129a63_5.7.0-rc1-ceph-g1457be129a63-1_amd64.deb | tar Ox --wildcards './usr/src/*/.config' | tee config-deb-5.7.0-rc1`


Generate .config from `kernel/build/kernel-config-deb.sh`
```
[root@lxbceph0 ceph-build]# git reset --hard f9eab4eb738636db07899f29a662fb14b7ab2bd5
HEAD is now at f9eab4e Merge pull request #1567 from ceph/wip-kernel-ubuntu-focal
[root@lxbceph0 ceph-build]#  kernel/build/kernel-config-deb.sh 
[root@lxbceph0 ceph-build]# cp .config /data/linux
cp: overwrite ‘/data/linux/.config’? y
[root@lxbceph0 ceph-build]# 
```

Checkout the `v5.7-rc1` and use the above `.config` do the `make menuconfig` with changing anything:

```
[root@lxbceph0 linux]# git checkout -b lxb-v5.7-rc1 v5.7-rc1
Checking out files: 100% (1161/1161), done.
Switched to a new branch 'lxb-v5.7-rc1'
[root@lxbceph0 linux]# make menuconfig
scripts/kconfig/mconf  Kconfig
.config:762:warning: symbol value 'm' invalid for HOTPLUG_PCI_SHPC
.config:912:warning: symbol value 'm' invalid for NF_CT_PROTO_DCCP
.config:913:warning: symbol value 'm' invalid for NF_CT_PROTO_GRE
.config:914:warning: symbol value 'm' invalid for NF_CT_PROTO_SCTP
.config:915:warning: symbol value 'm' invalid for NF_CT_PROTO_UDPLITE
.config:941:warning: symbol value 'm' invalid for NF_NAT_REDIRECT
.config:944:warning: symbol value 'm' invalid for NF_TABLES_INET
.config:1114:warning: symbol value 'm' invalid for NF_TABLES_IPV4
.config:1118:warning: symbol value 'm' invalid for NF_TABLES_ARP
.config:1155:warning: symbol value 'm' invalid for NF_TABLES_IPV6
.config:1389:warning: symbol value 'm' invalid for RXKAD
.config:1718:warning: symbol value 'm' invalid for SCSI_DH
.config:2350:warning: symbol value 'm' invalid for SERIAL_8250_FINTEK
.config:2396:warning: symbol value 'm' invalid for HW_RANDOM_TPM
.config:3264:warning: symbol value 'm' invalid for USB_ISP1760_HCD
.config:3945:warning: symbol value 'm' invalid for REMOTEPROC
configuration written to .config

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.
```


The following is the diff of them:

```
[root@lxbceph0 linux]# diff .config /data/config-deb-5.7.0-rc1 
3c3
< # Linux/x86 5.7.0-rc1 Kernel Configuration
---
> # Linux/x86_64 5.7.0-rc1 Kernel Configuration
7c7
< # Compiler: gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
---
> # Compiler: gcc (Ubuntu 8.1.0-5ubuntu1~16.04) 8.1.0
10,11c10,11
< CONFIG_GCC_VERSION=80301
< CONFIG_LD_VERSION=230000000
---
> CONFIG_GCC_VERSION=80100
> CONFIG_LD_VERSION=228000000
15d14
< CONFIG_CC_HAS_ASM_INLINE=y
[root@lxbceph0 linux]# 
```

**Comment by idryomov** [comment]
So I ran the diffs myself because I wanted to see the netfilter related changes and have them recorded in history.  Here is the deb config diff:
```
14a18
> CONFIG_CC_HAS_ASM_INLINE=y
1199,1201c1203,1205
< # CONFIG_NF_TABLES_INET is not set
< # CONFIG_NF_TABLES_NETDEV is not set
< # CONFIG_NFT_NUMGEN is not set
---
> CONFIG_NF_TABLES_INET=y
> CONFIG_NF_TABLES_NETDEV=y
> CONFIG_NFT_NUMGEN=m
1202a1207
> # CONFIG_NFT_FLOW_OFFLOAD is not set
1208a1214
> CONFIG_NFT_NAT=m
1213a1220
> CONFIG_NFT_REJECT_INET=m
1215a1223,1224
> CONFIG_NFT_FIB=m
> # CONFIG_NFT_FIB_INET is not set
1217,1221c1226,1235
< # CONFIG_NFT_SOCKET is not set
< # CONFIG_NFT_OSF is not set
< # CONFIG_NFT_TPROXY is not set
< # CONFIG_NFT_SYNPROXY is not set
< # CONFIG_NF_FLOW_TABLE is not set
---
> CONFIG_NFT_SOCKET=m
> CONFIG_NFT_OSF=m
> CONFIG_NFT_TPROXY=m
> CONFIG_NFT_SYNPROXY=m
> CONFIG_NF_DUP_NETDEV=m
> CONFIG_NFT_DUP_NETDEV=m
> CONFIG_NFT_FWD_NETDEV=m
> # CONFIG_NFT_FIB_NETDEV is not set
> CONFIG_NF_FLOW_TABLE_INET=m
> CONFIG_NF_FLOW_TABLE=m
1386,1387c1400,1405
< # CONFIG_NF_TABLES_IPV4 is not set
< # CONFIG_NF_TABLES_ARP is not set
---
> CONFIG_NF_TABLES_IPV4=y
> CONFIG_NFT_REJECT_IPV4=m
> CONFIG_NFT_DUP_IPV4=m
> CONFIG_NFT_FIB_IPV4=m
> CONFIG_NF_TABLES_ARP=y
> CONFIG_NF_FLOW_TABLE_IPV4=m
1423c1441,1445
< # CONFIG_NF_TABLES_IPV6 is not set
---
> CONFIG_NF_TABLES_IPV6=y
> CONFIG_NFT_REJECT_IPV6=m
> CONFIG_NFT_DUP_IPV6=m
> CONFIG_NFT_FIB_IPV6=m
> CONFIG_NF_FLOW_TABLE_IPV6=m
1459a1482
> CONFIG_NFT_BRIDGE_REJECT=m
1661a1685
> # CONFIG_NET_ACT_CT is not set
```

And here is the rpm config diff:
```
1167,1169c1170,1172
< # CONFIG_NF_TABLES_INET is not set
< # CONFIG_NF_TABLES_NETDEV is not set
< # CONFIG_NFT_NUMGEN is not set
---
> CONFIG_NF_TABLES_INET=y
> CONFIG_NF_TABLES_NETDEV=y
> CONFIG_NFT_NUMGEN=m
1170a1174
> # CONFIG_NFT_FLOW_OFFLOAD is not set
1177,1178c1181,1183
< # CONFIG_NFT_TUNNEL is not set
< # CONFIG_NFT_OBJREF is not set
---
> CONFIG_NFT_NAT=m
> CONFIG_NFT_TUNNEL=m
> CONFIG_NFT_OBJREF=m
1180c1185
< # CONFIG_NFT_QUOTA is not set
---
> CONFIG_NFT_QUOTA=m
1181a1187
> CONFIG_NFT_REJECT_INET=m
1183a1190,1191
> CONFIG_NFT_FIB=m
> # CONFIG_NFT_FIB_INET is not set
1185c1193
< # CONFIG_NFT_SOCKET is not set
---
> CONFIG_NFT_SOCKET=m
1189c1197,1202
< # CONFIG_NF_FLOW_TABLE is not set
---
> CONFIG_NF_DUP_NETDEV=m
> CONFIG_NFT_DUP_NETDEV=m
> CONFIG_NFT_FWD_NETDEV=m
> # CONFIG_NFT_FIB_NETDEV is not set
> CONFIG_NF_FLOW_TABLE_INET=m
> CONFIG_NF_FLOW_TABLE=m
1354,1355c1367,1372
< # CONFIG_NF_TABLES_IPV4 is not set
< # CONFIG_NF_TABLES_ARP is not set
---
> CONFIG_NF_TABLES_IPV4=y
> CONFIG_NFT_REJECT_IPV4=m
> CONFIG_NFT_DUP_IPV4=m
> CONFIG_NFT_FIB_IPV4=m
> CONFIG_NF_TABLES_ARP=y
> # CONFIG_NF_FLOW_TABLE_IPV4 is not set
1391c1408,1412
< # CONFIG_NF_TABLES_IPV6 is not set
---
> CONFIG_NF_TABLES_IPV6=y
> CONFIG_NFT_REJECT_IPV6=m
> CONFIG_NFT_DUP_IPV6=m
> CONFIG_NFT_FIB_IPV6=m
> CONFIG_NF_FLOW_TABLE_IPV6=m
1420a1442
> CONFIG_NFT_BRIDGE_REJECT=m
1422c1444
< # CONFIG_NF_CONNTRACK_BRIDGE is not set
---
> CONFIG_NF_CONNTRACK_BRIDGE=m
1623a1646
> # CONFIG_NET_ACT_CT is not set
```
Please update the commit message to include these diffs instead of those warnings and I'll merge.

**Comment by lxbsz** [comment]
@idryomov 
Done, please check. 
Thanks.

**Comment by idryomov** [comment]
Still some nits: it doesn't mention how the patch was generated or what those diffs are.  Use this:
```
kernel: update Kconfig templates to 5.7-rc5

Because of how "make olddefconfig" works, we were missing netfilter
options and couldn't configure INPUT/FORWARD/OUTPUT chains needed for
kcephfs suite (unshare_ns_mount.sh, mount.py).

Update our Kconfig templates to 5.7-rc5.  This has been generated
from the actual config (/boot/config-*) of one of the latest kernel
builds in shaman (as opposed to e.g. taking a distro config).

Here is the diff against the actual deb config:

14a18
> CONFIG_CC_HAS_ASM_INLINE=y
1199,1201c1203,1205
< # CONFIG_NF_TABLES_INET is not set
< # CONFIG_NF_TABLES_NETDEV is not set
< # CONFIG_NFT_NUMGEN is not set
---
> CONFIG_NF_TABLES_INET=y
> CONFIG_NF_TABLES_NETDEV=y
> CONFIG_NFT_NUMGEN=m
1202a1207
> # CONFIG_NFT_FLOW_OFFLOAD is not set
1208a1214
> CONFIG_NFT_NAT=m
1213a1220
> CONFIG_NFT_REJECT_INET=m
1215a1223,1224
> CONFIG_NFT_FIB=m
> # CONFIG_NFT_FIB_INET is not set
1217,1221c1226,1235
< # CONFIG_NFT_SOCKET is not set
< # CONFIG_NFT_OSF is not set
< # CONFIG_NFT_TPROXY is not set
< # CONFIG_NFT_SYNPROXY is not set
< # CONFIG_NF_FLOW_TABLE is not set
---
> CONFIG_NFT_SOCKET=m
> CONFIG_NFT_OSF=m
> CONFIG_NFT_TPROXY=m
> CONFIG_NFT_SYNPROXY=m
> CONFIG_NF_DUP_NETDEV=m
> CONFIG_NFT_DUP_NETDEV=m
> CONFIG_NFT_FWD_NETDEV=m
> # CONFIG_NFT_FIB_NETDEV is not set
> CONFIG_NF_FLOW_TABLE_INET=m
> CONFIG_NF_FLOW_TABLE=m
1386,1387c1400,1405
< # CONFIG_NF_TABLES_IPV4 is not set
< # CONFIG_NF_TABLES_ARP is not set
---
> CONFIG_NF_TABLES_IPV4=y
> CONFIG_NFT_REJECT_IPV4=m
> CONFIG_NFT_DUP_IPV4=m
> CONFIG_NFT_FIB_IPV4=m
> CONFIG_NF_TABLES_ARP=y
> CONFIG_NF_FLOW_TABLE_IPV4=m
1423c1441,1445
< # CONFIG_NF_TABLES_IPV6 is not set
---
> CONFIG_NF_TABLES_IPV6=y
> CONFIG_NFT_REJECT_IPV6=m
> CONFIG_NFT_DUP_IPV6=m
> CONFIG_NFT_FIB_IPV6=m
> CONFIG_NF_FLOW_TABLE_IPV6=m
1459a1482
> CONFIG_NFT_BRIDGE_REJECT=m
1661a1685
> # CONFIG_NET_ACT_CT is not set

Here is the diff against the actual rpm config:

1167,1169c1170,1172
< # CONFIG_NF_TABLES_INET is not set
< # CONFIG_NF_TABLES_NETDEV is not set
< # CONFIG_NFT_NUMGEN is not set
---
> CONFIG_NF_TABLES_INET=y
> CONFIG_NF_TABLES_NETDEV=y
> CONFIG_NFT_NUMGEN=m
1170a1174
> # CONFIG_NFT_FLOW_OFFLOAD is not set
1177,1178c1181,1183
< # CONFIG_NFT_TUNNEL is not set
< # CONFIG_NFT_OBJREF is not set
---
> CONFIG_NFT_NAT=m
> CONFIG_NFT_TUNNEL=m
> CONFIG_NFT_OBJREF=m
1180c1185
< # CONFIG_NFT_QUOTA is not set
---
> CONFIG_NFT_QUOTA=m
1181a1187
> CONFIG_NFT_REJECT_INET=m
1183a1190,1191
> CONFIG_NFT_FIB=m
> # CONFIG_NFT_FIB_INET is not set
1185c1193
< # CONFIG_NFT_SOCKET is not set
---
> CONFIG_NFT_SOCKET=m
1189c1197,1202
< # CONFIG_NF_FLOW_TABLE is not set
---
> CONFIG_NF_DUP_NETDEV=m
> CONFIG_NFT_DUP_NETDEV=m
> CONFIG_NFT_FWD_NETDEV=m
> # CONFIG_NFT_FIB_NETDEV is not set
> CONFIG_NF_FLOW_TABLE_INET=m
> CONFIG_NF_FLOW_TABLE=m
1354,1355c1367,1372
< # CONFIG_NF_TABLES_IPV4 is not set
< # CONFIG_NF_TABLES_ARP is not set
---
> CONFIG_NF_TABLES_IPV4=y
> CONFIG_NFT_REJECT_IPV4=m
> CONFIG_NFT_DUP_IPV4=m
> CONFIG_NFT_FIB_IPV4=m
> CONFIG_NF_TABLES_ARP=y
> # CONFIG_NF_FLOW_TABLE_IPV4 is not set
1391c1408,1412
< # CONFIG_NF_TABLES_IPV6 is not set
---
> CONFIG_NF_TABLES_IPV6=y
> CONFIG_NFT_REJECT_IPV6=m
> CONFIG_NFT_DUP_IPV6=m
> CONFIG_NFT_FIB_IPV6=m
> CONFIG_NF_FLOW_TABLE_IPV6=m
1420a1442
> CONFIG_NFT_BRIDGE_REJECT=m
1422c1444
< # CONFIG_NF_CONNTRACK_BRIDGE is not set
---
> CONFIG_NF_CONNTRACK_BRIDGE=m
1623a1646
> # CONFIG_NET_ACT_CT is not set

Fixes: https://tracker.ceph.com/issues/45531
Signed-off-by: Xiubo Li <xiubli@redhat.com>
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
```

**Comment by lxbsz** [comment]
Done and thanks @idryomov

**Pull request merged**
