### PR TITLE
Use createrepo_c, and change order of signing operations to avoid invalid repomd.xml sigs

### PR DESCRIPTION
**Pull request by dmick**
I couldn't validate repomd.xml.asc against repomd.xml without swapping these stanzas.

### CODE REVIEW

**Comment by ktdreyer** [comment]
This looks good to me.

**Review by ktdreyer — APPROVED** [review]

**Comment by ktdreyer** [comment]
I'm wondering how this ever worked. Does the script on the old signer VM match this copy in Git?

**Comment by ktdreyer** [comment]
Oh, I guess we always had bad signatures on `repomd.xml`.

For v17.2.5 today, the quincy el9 repository does not have a valid signature. Eg.

```
wget https://download.ceph.com/rpm-quincy/el9/x86_64/repodata/repomd.xml
wget https://download.ceph.com/rpm-quincy/el9/x86_64/repodata/repomd.xml.asc
wget https://download.ceph.com/keys/release.asc
gpg --import release.asc
gpg --verify repomd.xml.asc repomd.xml

gpg: Signature made Mon 17 Oct 2022 07:12:56 PM EDT
gpg:                using RSA key 08B73419AC32B4E966C1A330E84AC2C0460F3994
gpg: BAD signature from "Ceph.com (release key) <security@ceph.com>" [unknown]
```

**Comment by ktdreyer** [comment]
DNF does not validate these signatures by default. Users must set with `repo_gpgcheck=1` in the ceph .repo file in `/etc/yum.repos.d/`. By default the ceph-release RPM only sets `gpgcheck` (for the RPM files themselves), not `repo_gpgcheck`, so I guess it's not something any user would have found easily.

**Comment by ktdreyer** [comment]
I also had to look up the `--compatibility` flag in the createrepo_c source code. This activates two behavior changes:
- Keep all RPM `%changelog` entries in the metadata instead of the final 10. (Not relevant to Ceph upstream because we don't use RPM `%changelog` entries).
- Change the behavior of `--retain-old-md` to keep the last `NUM` of metadata instead of simply keeping all old entries. (Not relevant to Ceph because we don't use `--update`. We publish entirely fresh metadata every time for simplicity.)

**Comment by dmick** [comment]
re --compatibility: yeah, I just used it because it seemed safer to avoid any bad surprises

**Pull request merged**
