### PR TITLE
Modify scripts/{sync-pull,sign-rpms,sync-push} to handle ceph-iscsi

### PR DESCRIPTION
**Pull request by dmick**
All the tools and paths basically grow a "project" argument to distinguish ceph from ceph-iscsi.

In addition, drop el7, add vim modelines, and other minor cleanup.

### CODE REVIEW

**Comment by dmick** [comment]
This requires https://github.com/ceph/ceph-container/pull/2210 to use the new paths

**Comment by dmick** [comment]
This was tested for constructing the release of ceph-iscsi 3.8 and ceph 18.2.3

**Review by yuriw — APPROVED** [review]

**Comment by dmick** [comment]
retest

**Comment by dmick** [comment]
The test is failing, but there are no tests for these scripts (the test failure is unrelated). Merging.

**Pull request merged**
