### PR TITLE
ansible: Just use the example

### PR DESCRIPTION
**Pull request by djgalloway**
In our setup, the example is the canonical playbook that works.  If, for some reason, ceph-build.git is used by someone else, they can rm the symlink and create their own `ansible/slave.yml` but for our purposes, there's no need to keep separate playbooks as it just creates confusion when modifying the playbooks.

Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
It has to be there for prado to pick it up

**Comment by alfredodeza** [comment]
> It has to be there for prado to pick it up

So silly of this prado thing. Who implemented it that way?

**Comment by alfredodeza** [comment]
This looks OK to me, I'd rather update Prado at some point to allow cleaning up here. Prado allows configuration to what file is being called:

```python
build_map = {
    "slave": {
        "playbook_path": "%(confdir)s/../public/ceph-build/ansible",
        "playbook": "%(confdir)s/../public/ceph-build/ansible/slave.yml",
        "command": 'ansible-playbook -i "localhost," -c local ../main.yml'
    },
    "slave_libvirt": {
        "playbook_path": "%(confdir)s/../public/ceph-build/ansible",
        "playbook": "%(confdir)s/../public/ceph-build/ansible/slave_libvirt.yml",
        "command": 'ansible-playbook -i "localhost," -c local ../main.yml'
    },
    "slave_jnlp": {
        "playbook_path": "%(confdir)s/../public/ceph-build/ansible",
        "playbook": "%(confdir)s/../public/ceph-build/ansible/slave_jnlp.yml",
        "command": 'ansible-playbook -i "localhost," -c local ../main.yml'
    }
}
```

**Pull request merged**
