### PR TITLE
ceph-grafana: Update quay cred / erase dockerhub cred

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Review by epuertat — APPROVED** [review]
LGTM, but this also needs to be updated in `ceph-grafana-trigger/config/definition/ceph-grafana-trigger.yml` too (I don't get why we have 2 jobs for this... I'll look at improving this after the Quincy release is unblocked :S)

**Review by epuertat — APPROVED** [review]
👍🏼

**Comment by djgalloway** [comment]
> LGTM, but this also needs to be updated in `ceph-grafana-trigger/config/definition/ceph-grafana-trigger.yml` too (I don't get why we have 2 jobs for this... I'll look at improving this after the Quincy release is unblocked :S)

Fixed.

Because you need both x86 and arm64 containers.  AFAIK, you need a master/trigger job to trigger the separate arch jobs.

**Comment by epuertat** [comment]
> > LGTM, but this also needs to be updated in `ceph-grafana-trigger/config/definition/ceph-grafana-trigger.yml` too (I don't get why we have 2 jobs for this... I'll look at improving this after the Quincy release is unblocked :S)
> 
> Fixed.
> 
> Because you need both x86 and arm64 containers. AFAIK, you need a master/trigger job to trigger the separate arch jobs.

Mmm, I think that the api/e2e nightly jobs are just a single job spec, but with templates + matrix it's able to do multiple builds...

**Comment by djgalloway** [comment]
Yeah but this is for containers.  The trigger job is what makes and pushes the manifest.

**Pull request merged**
