### PR TITLE
Remove teuthology-pull-requests

### PR DESCRIPTION
**Pull request by zmc**
This job represents a small subset of what we test with GitHub Actions. It's also unreliable, for reasons including - but not limited to - the fact that it's not possible to request an agent with a particular OS version.

### CODE REVIEW

**Review by dmick — COMMENTED** [review]
Does the job still have a use if it doesn't trigger on PR?  Should we just remove the job?

**Comment by zmc** [comment]
> Does the job still have a use if it doesn't trigger on PR? Should we just remove the job?

I was writing out a reply to the effect of "maybe we should keep it in case we want it in the future" but then I realized if we ever revived it, it should be a pipeline - so no, I think we can just drop the whole job.

**Comment by dmick** [comment]
retest this please

**Comment by dmick** [comment]
retest this please

**Comment by dmick** [comment]
sigh.  retest this *again*, please

**Comment by dmick** [comment]
retest

**Review by dmick — APPROVED** [review]

**Pull request merged**
