### PR TITLE
ceph-pr,api-pr: Revert" skip when not needed"

### PR DESCRIPTION
**Pull request by tchaikov**
This reverts commit ae9a52ba2faa0b7faf0b9e0c6d3fd289cdd576ea.

### CODE REVIEW

**Review by callithea — APPROVED** [review]

**Review by epuertat — APPROVED** [review]
Thank you @tchaikov! It's a pity that this didn't work :(

**Comment by djgalloway** [comment]
@epuertat did you double check that this got templated out correctly in the Jenkins Web UI?  The Help for the plugin says "Each exclusion uses regular expression pattern matching, and must be separated by a new line." which I see you wrote here in the yaml.  I'm just curious if you needed to

```
do: |
  this
```

**Comment by epuertat** [comment]
@djgalloway, yup. I fixed some syntax issues from the 1st PR in the 2nd one (https://github.com/ceph/ceph-build/pull/1707), which resulted in the following UI config (I also tried with just `doc/`):

image

...but even though, it didn't catch a basic case (doc only change):

- https://github.com/ceph/ceph/pull/38115
- https://github.com/ceph/ceph/pull/38116
- https://github.com/ceph/ceph/pull/38117

I wish you detect any omission over there, but after Googling a bit, it seems that the issue has to do with the way the Jenkins `git-client` plugins provides the changeset list with a shallow clone (I also tried with a regular clone and with an incremental checkout, but no better luck).

**Comment by djgalloway** [comment]
Did you try `^doc/.*` ?

**Comment by epuertat** [comment]
> Did you try `^doc/.*` ?

No, I tried with both `^doc/` (a [Java regexp](https://www.freeformatter.com/java-regex-tester.html) should still match `doc/etc`) and just `doc`... Do you think that `^doc/.*` will fix this?

**Comment by djgalloway** [comment]
> > Did you try `^doc/.*` ?
> 
> Do you think that `^doc/.*` will fix this?

I think it's possible.  All of the examples they provide (except the single file `.gitignore`) have wildcards in them.  I wonder if the plugin is being super strict and looking for **only** the doc dir itself being changed (even though that's not a thing that would happen).

Here's the code: https://github.com/jenkinsci/ghprb-plugin/pull/293/files

**Comment by epuertat** [comment]
You were right! I tried with the following patterns and some of them worked:

image

The funny thing is that, the check doesn't run but Github still considers that as required, so the situation is rather weird:

image

I guess the only way to overcome this is that a single/required Jenkins pipeline check is required and that goes through a variable number of stages (sub-checks)....

**Comment by djgalloway** [comment]
> The funny thing is that, the check doesn't run but Github still considers that as required, so the situation is rather weird:

Ah, that's right.  I ran into this with the [ceph-pr-commits job](https://github.com/ceph/ceph-build/pull/1671).  In that instance, the job still runs but immediately "passes" If it's a docs only change.  That's not gonna work with the ghprb plugin.

**Pull request merged**
