### PR TITLE
script/build_utils.sh: don't fail if any mirror is not accessible

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
this should address failures like https://jenkins.ceph.com/job/ceph-dev-setup/14316//consoleFull

**Comment by alfredodeza** [comment]
I think these mirrors are not OK? This one is like a permanent 404 for me:

http://mirror.yandex.ru/mirrors/launchpad/ubuntu-toolchain-r/dists/xenial/main/i18n/Translation-en

**Comment by alfredodeza** [comment]
That is: there is no i18n in here:

http://mirror.yandex.ru/mirrors/launchpad/ubuntu-toolchain-r/dists/xenial/main/

**Comment by tchaikov** [comment]
@alfredodeza i noticed this. but i guess it's a temporary issue. also by "these mirrors", what do you mean in addition to yandex.ru one?

**Comment by tchaikov** [comment]
@alfredodeza i believe i've address this issue.

**Comment by ktdreyer** [comment]
Have we reported the PPA failure to the admins that run launchpad.net ?

**Comment by tchaikov** [comment]
@ktdreyer could you be more specific regarding to "the PPA failure"?

**Comment by ktdreyer** [comment]
Oh, this PR says "if any mirror is not accessible", so I thought all mirrors were offline.

**Pull request merged**
