### PR TITLE
*/build_deb: extract get_bptag() into build_utils.sh

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@djgalloway i am considering your question at https://github.com/ceph/ceph-build/pull/1715#issuecomment-737282224 . seems the question boils down to 

> do we still build on wheezy?

i'd vote for stopping building on wheezy, and starting building on a more recent debian stable release, "buster" for instance.

what do you think?

**Comment by djgalloway** [comment]
> @djgalloway i am considering your question at [#1715 (comment)](https://github.com/ceph/ceph-build/pull/1715#issuecomment-737282224) . seems the question boils down to
> 
> > do we still build on wheezy?
> 
> i'd vote for stopping building on wheezy, and starting building on a more recent debian stable release, "buster" for instance.
> 
> what do you think?

Yeah, we don't build for wheezy.  Haven't since Kraken at the latest.  I say scrap it!

```
Luminous (12.X.X): xenial centos7 trusty jessie stretch
Mimic (13.X.X): bionic xenial centos7
Nautilus (14.X.X): bionic xenial centos7 centos8
Octopus (15.X.X): focal bionic centos7 centos8 buster
Pacific (16.X.X): 
```

**Comment by tchaikov** [comment]
@djgalloway thanks. will remove the references to wheezy in another commit in this PR.

**Comment by tchaikov** [comment]
@djgalloway could you take another look? i've pushed the updated ceph-*build jobs to jenkins.

**Review by djgalloway — APPROVED** [review]
You're my hero

**Pull request merged**
