### PR TITLE
scripts: disable chacractl ssl verification temporarily

### PR DESCRIPTION
**Pull request by alfredodeza**
Signed-off-by: Alfredo Deza <adeza@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
that's what it does, but why?

**Comment by ktdreyer** [comment]
why

**Comment by andrewschoen** [comment]
@ktdreyer we were having trouble with letsencrypt so we thought it'd be important to also support self-signed certificates.

**Comment by ktdreyer** [comment]
Thank you!

**Pull request merged**
