### PR TITLE
programatically make the .chacractl file

### PR DESCRIPTION
**Pull request by andrewschoen**
This uses variables created by the masks-passwords jenkins plugin.

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
are these already set in jenkins?

**Comment by andrewschoen** [comment]
@alfredodeza nope, and I'm not even sure how to do that. Does this look like the correct way to do this though?

**Comment by alfredodeza** [comment]
yes this would be right, is there a need for the user and url to be masked? the key needs to be for sure

**Comment by ktdreyer** [comment]
To do it:

1. visit https://jenkins.ceph.com/configure
2. under "Global Properties", set the `CHACRACTL_USER` environment variable
3. scroll down and under "Global Passwords", set the `CHACRACTL_KEY` value

**Comment by andrewschoen** [comment]
@alfredodeza I don't plan to mask them, but doesn't hurt to make them configurable.

**Pull request merged**
