### PR TITLE
ceph-ansible-pr-syntax-check: change playbook path

### PR DESCRIPTION
**Pull request by leseb**
https://github.com/ceph/ceph-ansible/pull/1140 did a bit of cleanup and
regor so we have to modify the CI as well.

Do not merge before https://github.com/ceph/ceph-ansible/pull/1140

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
Does this mean ceph-installer will need to change as well?

**Comment by andrewschoen** [comment]
@ktdreyer yes, it would

**Comment by ktdreyer** [comment]
I wish we could have ceph-installer running on each change

**Comment by alfredodeza** [comment]
@leseb I don't think this is needed anymore right? can we close this PR?

**Comment by leseb** [comment]
@alfredodeza I've never resumed the refactor on ceph-ansible. That's not going to happen soon.
Closing this.

**Pull request closed without merging**
