### PR TITLE
build_utils: Don't build pacific containers for el7

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
jenkins retest

**Comment by djgalloway** [comment]
jenkins retest this please

**Comment by djgalloway** [comment]
jenkins retest this please

**Comment by djgalloway** [comment]
```
dgalloway@p50 ~ ()$ DIST=el7
dgalloway@p50 ~ ()$ BRANCH=nautilus
dgalloway@p50 ~ ()$     if [[ "$BRANCH" =~ octopus|pacific && "$DIST" == el7 ]]; then echo "disabling CI container build for $BRANCH"; fi
dgalloway@p50 ~ ()$ BRANCH=octopus
dgalloway@p50 ~ ()$     if [[ "$BRANCH" =~ octopus|pacific && "$DIST" == el7 ]]; then echo "disabling CI container build for $BRANCH"; fi
disabling CI container build for octopus
dgalloway@p50 ~ ()$ BRANCH=nautilus
dgalloway@p50 ~ ()$     if [[ "$BRANCH" =~ octopus|pacific && "$DIST" == el7 ]]; then echo "disabling CI container build for $BRANCH"; fi
dgalloway@p50 ~ ()$ BRANCH=pacific
dgalloway@p50 ~ ()$     if [[ "$BRANCH" =~ octopus|pacific && "$DIST" == el7 ]]; then echo "disabling CI container build for $BRANCH"; fi
disabling CI container build for pacific
```

**Review by dmick — APPROVED** [review]

**Pull request merged**
