### PR TITLE
ceph-ansible-prs: Stop using smithi

### PR DESCRIPTION
**Pull request by djgalloway**
They no longer have enough system resources to run all the VMs.

Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
@djgalloway these nodes can still be used for some jobs though

**Comment by djgalloway** [comment]
Okay.  Do you know which?

**Comment by guits** [comment]
I would say:

- lvm_osds
- shrink_*
- add_*
- rgw_multisite
- external_clients
- filestore_to_bluestore

basically, all jobs with few VMs required should be able to run on either smithi or ephemeral nodes

**Comment by djgalloway** [comment]
We took care of this in more recent PRs.

**Pull request closed without merging**
