### PR TITLE
ceph-dev-*build: build containers as root

### PR DESCRIPTION
**Pull request by liewegas**
Would this work?

### CODE REVIEW

**Comment by djgalloway** [comment]
Yeah, I mean, I can run `docker ps` on braggi05 right now and get the error.  It goes away with `sudo`.  I don't know what the implications are of doing the entire thing using sudo.  Interested to hear @dsavineau's input.

**Comment by dsavineau** [comment]
I didn't try it but I'm pretty sure it's ok to run the script as root via sudo

**Comment by liewegas** [comment]
hmm, i think we need to adjust the script some more:
```
+ sudo CI_CONTAINER=true SHA1=ca338cb74a4f503555323a668a2ba5b2e1845057 /bin/bash ./contrib/build-push-ceph-container-imgs.sh
+ CI_CONTAINER=true
+ true
+ CEPH_BRANCH=
+ for v in BRANCH SHA1 CONTAINER_REPO_HOSTNAME CONTAINER_REPO_ORGANIZATION CONTAINER_REPO_USERNAME CONTAINER_REPO_PASSWORD
+ require BRANCH
+ [[ -z '' ]]
+ echo 'Required variable BRANCH not set, exiting'
Required variable BRANCH not set, exiting
+ exit 1
```
https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/38989//consoleFull

**Comment by dsavineau** [comment]
maybe `sudo -E` ?

**Comment by tchaikov** [comment]
#1547 is a follow-up fix for this PR.

**Pull request merged**
