### PR TITLE
ceph-iscsi-stable: query correct chacra host for uploads

### PR DESCRIPTION
**Pull request by dillaman**
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
@dillaman what's this about?  Stable releases that will be signed and pushed to download.ceph.com should go to chacra.ceph.com, not one of the dev nodes.

**Comment by dillaman** [comment]
Gotcha -- I can revert it back. I was trying to diagnose why the upload failed w/ unauthorized, so I just copied the examples from other build scripts to query a chacra node and to specify the credentials in the jenkins job.

**Comment by djgalloway** [comment]
Oh, I didn't notice why the first job failed.  Let's see..

```
+ cd /home/jenkins-build/build/workspace/ceph-iscsi-stable
+ chacra_endpoint=ceph-iscsi/3/ec80bb1cc8b288b40bc35e03e4ba4c60daced938/centos/7
+ chacra_repo_endpoint=ceph-iscsi/3/ec80bb1cc8b288b40bc35e03e4ba4c60daced938/centos/7/flavors/default
+ '[' '!' -f /home/jenkins-build/build/workspace/ceph-iscsi-stable/dist/RPMS/ceph-iscsi-3.2-3.2.el7.noarch.rpm /home/jenkins-build/build/workspace/ceph-iscsi-stable/dist/RPMS/ceph-iscsi-3.2-3.2.el7.src.rpm /home/jenkins-build/build/workspace/ceph-iscsi-stable/dist/RPMS/ceph-iscsi-tools-2.1-2.1.el7.noarch.rpm /home/jenkins-build/build/workspace/ceph-iscsi-stable/dist/RPMS/ceph-iscsi-tools-2.1-2.1.el7.src.rpm ']'
/tmp/jenkins396895395388000516.sh: line 1143: [: too many arguments
+ '[' '!' -f /home/jenkins-build/build/workspace/ceph-iscsi-stable/dist/RPMS/ceph-iscsi-tools-2.1-2.1.el7.noarch.rpm /home/jenkins-build/build/workspace/ceph-iscsi-stable/dist/RPMS/ceph-iscsi-tools-2.1-2.1.el7.src.rpm ']'
/tmp/jenkins396895395388000516.sh: line 1149: [: /home/jenkins-build/build/workspace/ceph-iscsi-stable/dist/RPMS/ceph-iscsi-tools-2.1-2.1.el7.noarch.rpm: binary operator expected
```
That's my bad.  This is bad bash: `if [ ! -f $WORKSPACE/dist/RPMS/ceph-iscsi-*.rpm ]; then`

I'll fix that.

The job failed to upload to chacra.ceph.com because it was missing the `CHACRACTL_KEY` which you fixed in https://github.com/ceph/ceph-build/pull/1371

**Comment by dillaman** [comment]
I was actually referring to this error from the first build:

> [urllib3.connectionpool][DEBUG ] Starting new HTTPS connection (1): chacra.ceph.com:443
> [urllib3.connectionpool][DEBUG ] https://chacra.ceph.com:443 "POST /binaries/ceph-iscsi/3/ec80bb1cc8b288b40bc35e03e4ba4c60daced938/centos/7/source/ HTTP/1.1" 401 358
> [chacractl.api.binaries][WARNING] 401 -> <html>
>  <head>
>   <title>401 Unauthorized</title>
>  </head>
>  <body>
>   <h1>401 Unauthorized</h1>
>   This server could not verify that you are authorized to access the document you requested. Either you supplied the wrong credentials (e.g., bad password), or your browser does not understand how to supply the credentials required.<br /><br />
> 
> 
> 
>  </body>
> </html>
> Traceback (most recent call last):
>   File "/tmp/venv.P62b9DOQ6M/bin/chacractl", line 6, in <module>
>     main.ChacraCtl()
>   File "/tmp/venv.P62b9DOQ6M/lib/python2.7/site-packages/chacractl/main.py", line 38, in __init__
>     self.main(argv)
>   File "/tmp/venv.P62b9DOQ6M/lib/python2.7/site-packages/chacractl/decorators.py", line 68, in newfunc
>     return f(*a, **kw)
>   File "/tmp/venv.P62b9DOQ6M/lib/python2.7/site-packages/chacractl/main.py", line 82, in main
>     parser.dispatch()
>   File "/tmp/venv.P62b9DOQ6M/lib/python2.7/site-packages/tambo/dispatcher.py", line 21, in dispatch
>     result = instance.main()
>   File "/tmp/venv.P62b9DOQ6M/lib/python2.7/site-packages/chacractl/api/binaries.py", line 191, in main
>     self.post(url, filename)
>   File "/tmp/venv.P62b9DOQ6M/lib/python2.7/site-packages/chacractl/util.py", line 70, in inner_wrapper
>     value = function(*args, **kwargs)
>   File "/tmp/venv.P62b9DOQ6M/lib/python2.7/site-packages/chacractl/api/binaries.py", line 122, in post
>     response.raise_for_status()
>   File "/tmp/venv.P62b9DOQ6M/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://chacra.ceph.com/binaries/ceph-iscsi/3/ec80bb1cc8b288b40bc35e03e4ba4c60daced938/centos/7/source/

**Comment by djgalloway** [comment]
Yep, I figured that out :smile:.  Last sentence in my comment

**Pull request merged**
