### PR TITLE
[DNM] add ceph-osc test job set

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
Should be merged after #1363

**Comment by kshtsk** [comment]
This should be base on #1361 and #1363

**Comment by kshtsk** [comment]
This PR only for testing purpose

**Comment by djgalloway** [comment]
Is this needed anymore since we integrated `leap15` into all the existing ceph-dev* jobs?

**Comment by kshtsk** [comment]
@djgalloway thanks for the heads-up, I had an idea to have it merged, but looks like I've lost the interest, closing it now.

**Pull request closed without merging**
