### PR TITLE
scripts/build_utils.sh: use gcc-8 on bionic

### PR DESCRIPTION
**Pull request by tchaikov**
in hope to alleviate the ICE issues when building kvstore_tool.cc

see also https://bugzilla.redhat.com/show_bug.cgi?id=1531154

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-badone-testing-7/a25e9c88fde29b70b22a88433729d07266ac4de6/default/149807/

**Comment by alfredodeza** [comment]
I am neutral to this change. @ktdreyer do you have any opinion?

**Comment by liewegas** [comment]
@jamespage ?

**Comment by badone** [comment]
http://tracker.ceph.com/issues/38892

**Comment by javacruft** [comment]
:+1:

**Pull request merged**
