### PR TITLE
ceph-*build: pass --profiles nocheck to pbuilder

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
@djgalloway could you please help review this change?

**Comment by djgalloway** [comment]
:heart: :heart: :heart:

Have you tried manually pushing this to see if it breaks anything yet?

Can we look into getting rid of all the `HACK HACK HACK` hacks?

**Comment by tchaikov** [comment]
> ❤️ ❤️ ❤️
> 
> Have you tried manually pushing this to see if it breaks anything yet?

just pushed. testing now.

> 
> Can we look into getting rid of all the `HACK HACK HACK` hacks?

sure. probably in a cold rainy Sunday afternoon.

**Comment by djgalloway** [comment]
I'm on PTO tomorrow and would be more comfortable merging this next week if that's okay.

**Review by djgalloway — APPROVED** [review]

**Comment by tchaikov** [comment]
@djgalloway sure, will hold back until next week.

**Pull request merged**
