### PR TITLE
Fix broken jenkins-job-builder job

### PR DESCRIPTION
**Pull request by zmc**
I'm unsure if this is exactly the right way to solve the issues I saw, but here's my rationale:

When the jjb job executes, sometimes it picks adami02, whose system python is 3.6; newer jjb versions appear to require `dataclasses`, which was new in 3.7 - a version that itself is EOL.

Other times, braggi02 gets selected. That host has 3.10, but was failing because of a lack of `wheel`.

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by dmick** [comment]
:+1:

**Comment by guits** [comment]
@zmc @dmick I wonder if that changes got well applied in jenkins after it got merged.

I'm still seeing the `dataclasses` error https://2.jenkins.ceph.com/job/jenkins-job-builder/818/console

**Comment by akraitman** [comment]
Hey @zmc I added "dataclasses" to the pkgs varible in the jenkins-job-builder config since it didn't pickup the changs while the job is failling

**Comment by dmick** [comment]
@akraitman I don't understand; one commit in Zack's change was to add dataclasses.  What do you mean you added dataclasses?

**Comment by akraitman** [comment]
@dmick What I meant is that since doing changes to "jenkins-job-builder/build/build" will only take affect when the jenkins-job-builder job is completed sucessfuly and in our case since the job is failing the change Zack did(adding dataclasses) won't be implmented in the job config, so what I did is I added "dataclasses" manully to the job config so from now on it will read the change Zack did in jenkins-job-builder/build/build

**Comment by dmick** [comment]
Thanks, I get it now.  Did you do that for both jenkins hosts?

**Comment by akraitman** [comment]
On the first instance (jenkins.ceph.com) the job didn't fail, it picked up adami01 which has a newer python version

**Pull request merged**
