### PR TITLE
also remove venv that is left behind

### PR DESCRIPTION
**Pull request by alfredodeza**
Signed-off-by: Alfredo Deza <adeza@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
we don't want "wipe workspace" ?

**Comment by alfredodeza** [comment]
I don't know. Maybe? I was just finding that venv was left behind and had to `rm -rf` manually

**Comment by alfredodeza** [comment]
Can try using `wipe workspace`

**Comment by alfredodeza** [comment]
@ktdreyer we can't use `wipe-workspace: true` because that is an `scm` option that will remove/wipe the previous cloned repository. This `venv` directory exists outside of the cloned repository so that option will not help in this particular case.

**Comment by ktdreyer** [comment]
Ok that makes sense then!

**Comment by ktdreyer** [comment]
https://github.com/ceph/ceph-build/pull/265 will clarify the "workarea" comment in this vicinity

**Pull request merged**
