### PR TITLE
replace version number in CMakeLists.txt if it exists

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
@alfredodeza could you help take a look? as we are switching to cmake. if would be desirable to cut the release using cmake also.

**Comment by tchaikov** [comment]
```
+ for playbook in '$WORKSPACE/ansible/examples/*.yml'
+ /home/jenkins-build/build/workspace/ceph-build-pull-requests/venv/bin/ansible-playbook -i 127.0.0.1, '/home/jenkins-build/build/workspace/ceph-build-pull-requests/ansible/examples/*.yml' --syntax-check
ERROR! the playbook: /home/jenkins-build/build/workspace/ceph-build-pull-requests/ansible/examples/*.yml could not be found
``` 

the test failure is not relevant.

**Comment by tchaikov** [comment]
but per https://github.com/ceph/ceph-build/blob/master/ceph-build-pull-requests/build/build#L28
```sh
# Syntax-check each Ansible playbook
for playbook in $WORKSPACE/ansible/*.yml; do
    $VENV/ansible-playbook -i '127.0.0.1,' $playbook --syntax-check
done
```
we are not checking the `example/*.yml`. @ktdreyer @alfredodeza do you have any idea why?

**Comment by alfredodeza** [comment]
@tchaikov I moved them to a different location. Sorry about that, will have a fix shortly

**Comment by alfredodeza** [comment]
test this please

**Pull request merged**
